# Generated by Django 4.2.2 on 2023-06-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishTimeClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('finish_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoclass',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='todoclass',
            name='todo',
        ),
        migrations.AddField(
            model_name='todoclass',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='todoclass',
            name='star',
            field=models.BooleanField(default=False, verbose_name='Star'),
        ),
        migrations.AddField(
            model_name='todoclass',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoclass',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todoclass',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='todoclass',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='PlayListClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('finished', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.finishtimeclass', verbose_name='playlist_finished')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todoclass', verbose_name='plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'playlist',
                'verbose_name_plural': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlanClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('finished', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.finishtimeclass', verbose_name='plan_finish')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoclass', verbose_name='plan')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plan',
            },
        ),
        migrations.CreateModel(
            name='MyDayClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoclass', verbose_name='myday')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'myday',
                'verbose_name_plural': 'myday',
            },
        ),
        migrations.CreateModel(
            name='ImportantClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoclass', verbose_name='important')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'important',
                'verbose_name_plural': 'important',
            },
        ),
    ]
